### ISSUE TITLE
Error importing data in icingaweb2 with director

### ISSUE THREAD

**Issue by thammw** [Icinga/icingaweb2-module-vsphere#10]
In the documentation ( [Documentation](https://github.com/Icinga/icingaweb2-module-vsphere/blob/master/doc/03-Import-Source.md )) about the vsphere feature following is shown:

![grafik](https://user-images.githubusercontent.com/30145976/31007100-9ec0780e-a4ff-11e7-8bac-dd633a06beac.png)

Whereas as I tried to import data from our vcenter i couldn't get a connection with https://* 
In the corresponding error :
#0 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/CurlLoader.php(184): Icinga\Module\Vsphere\CurlLoader->request('post', 'https://https:/...', '<?xml version="...', Array) .

Filling the field without "https://" did the trick then.
 I don't know if it's a big deal to leave both options open (if "https://*" exists in the string to not add it to the curl query).

**Comment by h3ge** [comment]
I don't think this is a bug, there is a own field for the protocol where you can define https or http.

In the description you can find this info "Usually this is just a fully qualified domain name (and should match it's certificate. Alternatively, an IP address is fine. Please use <host>:<port> in case you're not using default HTTP(s) ports" - so an url is not needed.

**Comment by Thomas-Gelf** [comment]
Well, it's a documentation bug, kind of. Form field and description text are correct, as @h3ge correctly states. But the screen-shot in the documentation shown by @thammw is from an earlier version where that field expected a full URL instead of just the host.

**Comment by thammw** [comment]
It's not really a bug. I can confirm. Just wanted it to be known. :)
Thx for confirming!

**Comment by Thomas-Gelf** [comment]
Thanks for reporting it!
