### ISSUE TITLE
CURL ERROR: SSL certificate problem: unable to get local issuer certificate)

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2-module-vsphere#21]
im trying to add my vcenter. (vcenter is working with a self signed cert.)
and i get the following error:

#0 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/CurlLoader.php(173): Icinga\Module\Vsphere\CurlLoader->request(String, String, NULL)
#1 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(175): Icinga\Module\Vsphere\CurlLoader->get(String)
#2 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(131): Icinga\Module\Vsphere\Api->prepareWsdl()
#3 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(110): Icinga\Module\Vsphere\Api->soapClient()
#4 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(233): Icinga\Module\Vsphere\Api->soapCall(String, Object(SoapVar))
#5 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(191): Icinga\Module\Vsphere\Api->fetchServiceInstance()
#6 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(251): Icinga\Module\Vsphere\Api->getServiceInstance()
#7 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/ProvidedHook/Director/ImportSource.php(28): Icinga\Module\Vsphere\Api->login()
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(109): Icinga\Module\Vsphere\ProvidedHook\Director\ImportSource->fetchData()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/SimpleQueryBasedTable.php(15): dipl\Web\Table\SimpleQueryBasedTable->getQuery()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(56): dipl\Web\Table\SimpleQueryBasedTable->getPaginationAdapter()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(237): dipl\Web\Table\QueryBasedTable->getPaginator(Object(dipl\Web\Url))
#13 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(157): dipl\Web\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#20 {main}

is there a way to ignore self signed certificates ???

**Comment by Thomas-Gelf** [comment]
I guess "Verify Peer" is what you're looking for, there is a screenshot in the [documentation](https://github.com/Icinga/icingaweb2-module-vsphere/blob/master/doc/03-Import-Source.md):

![Configuration](https://raw.githubusercontent.com/Icinga/icingaweb2-module-vsphere/master/doc/screenshot/03_import-source/035_configure-connection.png)

**Comment by ChristianMoritz** [comment]
only with setting both (verify host & verify peer) to NO it seems to work now.
thanks

**Comment by RamiSingh** [comment]
@ChristianMoritz  Thanks. Setting both (verify host & verify peer) to NO, made it work.
