### ISSUE TITLE
Sync rules fail on ESXi import Source

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-vsphere#5]
When trying to trigger a Sync run from an ESXi import source, the Icinga Director fails with the following message:

This Sync Rule failed when last checked at 2017-07-05 10:50:42: Data is not nested, cannot access runtime.host: stdClass::__set_state(array( 'runtime' => NULL, 'guest' => NULL, 'config' => NULL, 'name' => 'virtual-machine', ))

The problem seems to be the '.' of 'runtime.host'.

Using modifiers on the import source to remove the '.' from the column resolves the issue and the sync run is working properly.

**Comment by Thomas-Gelf** [comment]
I'll restructure the default properties and ship dictionaries, so runtime, guest and config would be main keys. Accessing their keys would then work as it should, via runtime.host and similar.
