### ISSUE TITLE
Empty fields in import source preview in 1.1

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-vsphere#6]
Hi,

in the import source preview nearly all fields(like config.product.apiVersion, guest.guestFullName) are empty except of the fields: name, parent, and vm. It seems there is an issue with the new datatypes in v1.1.

![image](https://user-images.githubusercontent.com/25796110/28524983-f79beea6-7082-11e7-918c-f23f3a0d7b4a.png)

**Comment by Thomas-Gelf** [comment]
Hi @cstegm,

that's "correct". We changed data to structured data in 1.1.0 and broke compatibility. This causes shown preview issues, but the data feels more "natural" and correct this way. You should find all properties scrolling to the right in the Hashes/Dictionaries named config, guest etc. The module still tells Director about those flat keys, and we do not want to drop them - as it makes configuring Sync Rules easier. Director v1.4.0 will "understand" this and no longer show those obsolete (and empty) columns in the preview any more.

But apart from this UI issue in the preview, Import and Sync should work fine - is this true?

Cheers,
Thomas

**Comment by cstegm** [comment]
Hi @Thomas-Gelf, 

yes, import and sync works fine. 

Cheers
Christopher
