### ISSUE TITLE
Erraneous hook implementation, class does not exist

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-vsphere#7]
When I activate this modul and then go to Director -> Import Source -> "Add" I got the following error with stacktrace:
Erraneous hook implementation, class "Icinga\Module\Director-vsphere\ProvidedHook\Director\ImportSource" does not exist
```
#0 /usr/share/php/Icinga/Application/Hook.php(267): Icinga\Application\Hook::createInstance('Director\\Import...', 'Icinga\\Module\\D...')
#1 /usr/share/icingaweb2/modules/director/application/forms/ImportSourceForm.php(141): Icinga\Application\Hook::all('Director\\Import...')
#2 /usr/share/icingaweb2/modules/director/application/forms/ImportSourceForm.php(35): Icinga\Module\Director\Forms\ImportSourceForm->enumSourceTypes()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(356): Icinga\Module\Director\Forms\ImportSourceForm->setup()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(499): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(512): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#7 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(47): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->addAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addAction')
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}
```
When I disable the modul icingaweb2-module-vsphere, the Import source "Add" page will work again.

## Steps to Reproduce (for bugs)
1. Git clone Repo to /usr/share/icingaweb2/modules/director-vsphere
2. Enable Modul in icinga web
3. Go to the Director -> Import Source and click on "Add"

## Your Environment
* Director-vsphere Modul: master/1.1.0 (last update: 28.08.2017)
* Director version: master (last update: 28.08.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, PHP versions: Apache 2.4.25-3+deb9u2, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
Your directory should be `vsphere`, not `director-vsphere`. Every module in Icinga Web 2 must sit in a directory fitting it's module name. Documentation for this module says:

> Download the latest version and extract it to a folder named `vsphere` in one of your Icinga Web 2 module path directories.
