### ISSUE TITLE
Feature Request: Add property for operatingsystem

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-vsphere#9]
I would need the Source Column (in Properties of a Sync rule) "guest.operatingsystem" for the info what operating system run on that virtual machine. For Windows hosts I sync this from Windows AD, but for Linux I need this information from VMware.

VMware has the info via config or via VMware Tools. In the GUI it shows the config value, when it does not can read out via VMware Tools. Not sure, which information you can read out from the VMware API. Perfect would be that same behavior, so there is always an info. Otherwise, we need two new fields. Possible example: "guest.operatingsystem" (config) and "runtime.operatingsystem" (info from VMware Tools).

Many thanks in advance.

**Comment by Thomas-Gelf** [comment]
Could `guest.guestId` eventually be what you're looking for? I have no test environment here right now, but as far as I remember that property should always be available, even without running guest utilities. That's the OS you specify when creating a VM - and might not reflect reality. Please look [here](https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html) for a list of possible values.

Eventually create a *Data List* in Director with mappings for the operating systems you need and use the *Map* Import Modifier to map imported values to their "nice" name.

**Comment by pmalsenz** [comment]
The OS field is already available: `guest.guestFullName`

Some column and field descriptions from VMware could use a bit improvement ;-)

**Comment by Naro370** [comment]
Thank you both, guest.guestId and guest.guestFullName are exactly that what I need.
Imho the names are named misleading. guestOsId and guestOsFullName would be better.
In first placed I thought that guestId is the internal id from vmware for that virtual maschine.
